from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol

from ratvision.domain.models import DisplayInfo, ForegroundProcess, VisualParameters


ForegroundCallback = Callable[[ForegroundProcess], None]


class PlatformUnavailableError(RuntimeError):
    pass


class ForegroundWindowProvider(Protocol):
    def start(self, callback: ForegroundCallback) -> None: ...
    def stop(self) -> None: ...
    def current(self) -> ForegroundProcess: ...


class DisplayProvider(Protocol):
    def list_displays(self) -> list[DisplayInfo]: ...


class ColorBackend(Protocol):
    def capture(self, display_id: str) -> None: ...
    def apply(self, display_id: str, params: VisualParameters) -> None: ...
    def restore(self, display_id: str) -> None: ...
    def restore_all(self) -> None: ...
    def capabilities(self, display_id: str) -> dict[str, Any]: ...


class TrayBackend(Protocol):
    def start(self, actions: Any) -> None: ...
    def set_enabled(self, enabled: bool) -> None: ...
    def stop(self) -> None: ...


class StartupBackend(Protocol):
    def is_enabled(self) -> bool: ...
    def set_enabled(self, value: bool) -> None: ...
